hyperparameters:
  model: "SAC"
  epochs: 100
  lr: 0.0001
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  noise: 0.1

memory:
  buffer_size: 10000
  batch_size: 64

checkpoint:
  save_freq: 200
  save_only_best: true


env:
  env_name: "Pendulum-v0"
